"""
Theme Converter
Convert between different theme formats (Terminal JSON, QSS, CustomTkinter, Windows Terminal)
"""

from .theme_data import TerminalTheme, QSSPalette, CustomTkinterTheme


class ThemeConverter:
    """Convert themes between different formats"""

    @staticmethod
    def terminal_to_qss(terminal_theme: TerminalTheme, name: str = "Converted") -> tuple[QSSPalette, str]:
        """
        Convert Terminal theme to QSS palette and stylesheet

        Mapping strategy:
        - background → background
        - foreground → foreground
        - blue → primary (main action color)
        - brightBlue → hover (lighter action color)
        - brightBlack → border
        - selection → selected
        - brightWhite → hover background
        - brightBlack → disabled

        Args:
            terminal_theme: TerminalTheme object
            name: Name for the generated QSS theme

        Returns:
            Tuple of (QSSPalette, qss_code)
        """
        # Create QSS palette from terminal colors
        palette = QSSPalette(
            background=terminal_theme.background,
            foreground=terminal_theme.foreground,
            primary=terminal_theme.blue,           # Use blue as primary action color
            secondary=terminal_theme.cyan,         # Use cyan as secondary
            border=terminal_theme.brightBlack,     # Use bright black for borders
            hover=terminal_theme.selection,        # Use selection color for hover
            selected=terminal_theme.blue,          # Use blue for selected items
            disabled=terminal_theme.brightBlack    # Use bright black for disabled
        )

        # Generate QSS from palette
        qss_code = palette.generate_qss()

        # Add comment header
        header = f"""/* QSS Theme Generated from Terminal Theme: {terminal_theme.name} */
/* Conversion Date: Auto-generated by Theme Editor */

"""
        qss_code = header + qss_code

        return palette, qss_code

    @staticmethod
    def qss_to_terminal(qss_palette: QSSPalette, name: str) -> TerminalTheme:
        """
        Convert QSS palette to Terminal theme

        Mapping strategy (reverse of terminal_to_qss):
        - background → background
        - foreground → foreground
        - primary → blue
        - secondary → cyan
        - border → brightBlack
        - selected → selection

        Remaining colors generated based on palette:
        - red/green/yellow derived from primary hue
        - bright variants are lighter versions

        Args:
            qss_palette: QSSPalette object
            name: Name for the terminal theme

        Returns:
            TerminalTheme object
        """
        # Direct mappings
        background = qss_palette.background
        foreground = qss_palette.foreground
        blue = qss_palette.primary
        cyan = qss_palette.secondary
        brightBlack = qss_palette.border
        selection = qss_palette.selected

        # Generate complementary colors based on palette
        # For now, use a simple strategy: derive from primary color
        # In a more advanced version, we could use color theory

        # Parse primary color to generate variants
        primary_rgb = ThemeConverter._hex_to_rgb(qss_palette.primary)

        # Generate ANSI colors with color theory
        # Red: shift hue towards red
        red = ThemeConverter._shift_hue(primary_rgb, -120)  # Shift towards red
        brightRed = ThemeConverter._lighten(red, 1.3)

        # Green: shift hue towards green
        green = ThemeConverter._shift_hue(primary_rgb, 120)  # Shift towards green
        brightGreen = ThemeConverter._lighten(green, 1.3)

        # Yellow: between red and green
        yellow = ThemeConverter._shift_hue(primary_rgb, 60)
        brightYellow = ThemeConverter._lighten(yellow, 1.3)

        # Blue: use primary
        brightBlue = ThemeConverter._lighten(primary_rgb, 1.3)

        # Purple: shift towards magenta
        purple = ThemeConverter._shift_hue(primary_rgb, -60)
        brightPurple = ThemeConverter._lighten(purple, 1.3)

        # Cyan: use secondary
        brightCyan = ThemeConverter._lighten(ThemeConverter._hex_to_rgb(cyan), 1.3)

        # Black and white from background/foreground
        black = ThemeConverter._darken(ThemeConverter._hex_to_rgb(background), 0.8)
        white = ThemeConverter._lighten(ThemeConverter._hex_to_rgb(foreground), 0.8)
        brightWhite = ThemeConverter._lighten(ThemeConverter._hex_to_rgb(foreground), 1.2)

        # Cursor: use foreground
        cursor = foreground

        # Create terminal theme
        return TerminalTheme(
            name=name,
            background=background,
            foreground=foreground,
            cursor=cursor,
            selection=selection,
            black=ThemeConverter._rgb_to_hex(black),
            red=red,
            green=green,
            yellow=yellow,
            blue=blue,
            purple=purple,
            cyan=cyan,
            white=white,
            brightBlack=brightBlack,
            brightRed=brightRed,
            brightGreen=brightGreen,
            brightYellow=brightYellow,
            brightBlue=brightBlue,
            brightPurple=brightPurple,
            brightCyan=brightCyan,
            brightWhite=brightWhite
        )

    @staticmethod
    def json_to_windows_terminal(terminal_theme: TerminalTheme) -> dict:
        """
        Convert Terminal JSON theme to Windows Terminal scheme format

        Args:
            terminal_theme: TerminalTheme object

        Returns:
            Windows Terminal scheme dict
        """
        # Windows Terminal uses same structure as JSON terminal themes
        return terminal_theme.to_dict()

    @staticmethod
    def windows_terminal_to_json(wt_scheme: dict) -> TerminalTheme:
        """
        Convert Windows Terminal scheme to Terminal JSON theme

        Args:
            wt_scheme: Windows Terminal scheme dict

        Returns:
            TerminalTheme object
        """
        # Windows Terminal uses same structure as JSON terminal themes
        return TerminalTheme.from_dict(wt_scheme)

    # ==================== Color Utility Methods ====================

    @staticmethod
    def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
        """Convert hex color to RGB tuple"""
        hex_color = hex_color.lstrip('#')
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))

    @staticmethod
    def _rgb_to_hex(rgb: tuple[int, int, int]) -> str:
        """Convert RGB tuple to hex color"""
        r, g, b = [max(0, min(255, int(c))) for c in rgb]  # Clamp to 0-255
        return f"#{r:02X}{g:02X}{b:02X}"

    @staticmethod
    def _lighten(rgb: tuple[int, int, int], factor: float) -> str:
        """
        Lighten RGB color by factor

        Args:
            rgb: RGB tuple (r, g, b)
            factor: Lightening factor (>1.0)

        Returns:
            Hex color string
        """
        r, g, b = rgb
        r = int(min(255, r * factor))
        g = int(min(255, g * factor))
        b = int(min(255, b * factor))
        return ThemeConverter._rgb_to_hex((r, g, b))

    @staticmethod
    def _darken(rgb: tuple[int, int, int], factor: float) -> tuple[int, int, int]:
        """
        Darken RGB color by factor

        Args:
            rgb: RGB tuple (r, g, b)
            factor: Darkening factor (<1.0)

        Returns:
            RGB tuple
        """
        r, g, b = rgb
        r = int(max(0, r * factor))
        g = int(max(0, g * factor))
        b = int(max(0, b * factor))
        return (r, g, b)

    @staticmethod
    def _shift_hue(rgb: tuple[int, int, int], degrees: int) -> str:
        """
        Shift hue of RGB color by degrees

        Args:
            rgb: RGB tuple (r, g, b)
            degrees: Degrees to shift hue (-360 to 360)

        Returns:
            Hex color string
        """
        # Convert RGB to HSL
        r, g, b = [c / 255.0 for c in rgb]
        max_c = max(r, g, b)
        min_c = min(r, g, b)
        l = (max_c + min_c) / 2

        if max_c == min_c:
            h = s = 0  # Achromatic
        else:
            d = max_c - min_c
            s = d / (2 - max_c - min_c) if l > 0.5 else d / (max_c + min_c)

            if max_c == r:
                h = (g - b) / d + (6 if g < b else 0)
            elif max_c == g:
                h = (b - r) / d + 2
            else:
                h = (r - g) / d + 4

            h /= 6

        # Shift hue
        h = (h * 360 + degrees) % 360
        h /= 360

        # Convert HSL back to RGB
        if s == 0:
            r = g = b = l
        else:
            def hue_to_rgb(p, q, t):
                if t < 0:
                    t += 1
                if t > 1:
                    t -= 1
                if t < 1/6:
                    return p + (q - p) * 6 * t
                if t < 1/2:
                    return q
                if t < 2/3:
                    return p + (q - p) * (2/3 - t) * 6
                return p

            q = l * (1 + s) if l < 0.5 else l + s - l * s
            p = 2 * l - q
            r = hue_to_rgb(p, q, h + 1/3)
            g = hue_to_rgb(p, q, h)
            b = hue_to_rgb(p, q, h - 1/3)

        r_int = int(r * 255)
        g_int = int(g * 255)
        b_int = int(b * 255)

        return ThemeConverter._rgb_to_hex((r_int, g_int, b_int))
